/*flexberryautogenerated="true"*/

namespace IIS.Склад
{
    using ICSSoft.STORMNET;
    using ICSSoft.STORMNET.Web.Controls;
    using ICSSoft.STORMNET.Web.AjaxControls;
    using ICSSoft.STORMNET.Web.Tools;
    using System;
    using System.Collections.Generic;
    using ICSSoft.STORMNET.Business;
    using ICSSoft.STORMNET.Business.LINQProvider;
    using System.Linq;
    using ICSSoft.STORMNET.Windows.Forms;
    using ICSSoft.STORMNET.FunctionalLanguage;

    public partial class СкладE : BaseEditForm<Склад>
    {
        /// <summary>
        /// Конструктор формы.
        /// </summary>
        public СкладE()
            : base(Склад.Views.СкладE)
        {
        }

        /// <summary>
        /// Путь до формы.
        /// </summary>
        public static string FormPath
        {
            get { return "~/forms/Sklad/SkladE.aspx"; }
        }

        /// <summary>
        /// Вызывается самым первым в Page_Load.
        /// </summary>
        protected override void Preload()
        {
            ctrlТоварНаСкладе.Operations.Delete = false;
            ctrlТоварНаСкладе.Operations.Add = false;
            ctrlТоварНаСкладе.Operations.PlusInRow = false;
            ctrlТоварНаСкладе.Operations.DeleteInRow = false;
        }

        /// <summary>
        /// Здесь лучше всего писать бизнес-логику, оперируя только объектом данных.
        /// </summary>
        protected override void PreApplyToControls()
        {
            //подсчитываем количество товаров на складе
            if (!IsPostBack && (DataObject == null || DataObject.GetStatus(true) != ObjectStatus.Created))
            {
                var ds = (SQLDataService)DataServiceProvider.DataService;
                var всеПоставки = ds.Query<Поставки>(Поставки.Views.ПоставкиL);
                var query = from п in всеПоставки
                                    where п.Склад == DataObject
                                    select п;
                List<Поставки> поставкиНаСклад = query.ToList(); 
                List<Поставки> сгруппированныеПоставки = поставкиНаСклад.GroupBy(t => t.Товар)
                    .Select(cl => new Поставки
                    {
                        Товар = cl.First().Товар,
                        Количестсво = cl.Sum(q => q.Количестсво),
                    }).ToList();
                var склад = new Склад();
                сгруппированныеПоставки.ForEach(delegate (Поставки name)
                {
                    var товарНаСкладе = new ТоварНаСкладе { Товар = name.Товар, Количество = name.Количестсво };
                    DataObject.ТоварНаСкладе.Add(товарНаСкладе); 
                });
                    //DataObject.ТоварНаСкладе.Add(foots);
            }
        }

        /// <summary>
        /// Здесь лучше всего изменять свойства контролов на странице,
        /// которые не обрабатываются WebBinder.
        /// </summary>
        protected override void PostApplyToControls()
        {
            Page.Validate();
        }

        /// <summary>
        /// Вызывается самым последним в Page_Load.
        /// </summary>
        protected override void Postload()
        {
        }

        /// <summary>
        /// Валидация объекта для сохранения.
        /// </summary>
        /// <returns>true - продолжать сохранение, иначе - прекратить.</returns>
        protected override bool PreSaveObject()
        {
            return base.PreSaveObject();
        }

        /// <summary>
        /// Нетривиальная логика сохранения объекта.
        /// </summary>
        /// <returns>Объект данных, который сохранился.</returns>
        protected override DataObject SaveObject()
        {
            return base.SaveObject();
        }
    }
}